name: mensaje_abrir_issue_Otras caracteristicas
on: 
  issues:
    types: opened
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [6, 8, 10]
    steps:
      - run: echo "Caso ${{ matrix.node }} "
